---
env:
  contexts:
    - name: juice-shop
      urls:
        - http://juice-shop:3000
      includePaths:
        - '^http://juice-shop:3000(?:$|[/?#].*)$'
      authentication:
        method: json
        parameters:
          loginPageUrl: http://juice-shop:3000/rest/user/login
          loginRequestUrl: http://juice-shop:3000/rest/user/login
          loginRequestBody: '{"email":"{%username%}","password":"{%password%"}'
        verification:
          method: response
          loggedOutRegex: '(?i)invalid email or password|unauthorized'
          loggedInRegex: '"status"\s*:\s*"success"'
      sessionManagement:
        method: headers
        parameters:
          headerName: Authorization
          headerPayload: Bearer {%response:json:data.token%}
      users:
        - name: user
          credentials:
            username: user@juice-sh.op
            password: user123
  configs:
    view.mode: protect
    scanner.maxScanDurationInMins: 30
  parameters:
    failOnError: true
    failOnWarning: false
    continueOnFailure: false
    progressToStdout: true

jobs:
  - type: passiveScan-config
    parameters:
      scanOnlyInScope: true
  - type: spider
    parameters:
      context: juice-shop
      user: user
      url: http://juice-shop:3000
      maxDuration: 10
  - type: spiderClient
    parameters:
      context: juice-shop
      user: user
      url: http://juice-shop:3000
      maxDuration: 10
      scopeCheck: Strict
  - type: passiveScan-wait
    parameters:
      maxDuration: 10
  - type: activeScan
    parameters:
      context: juice-shop
      user: user
      url: http://juice-shop:3000
  - type: passiveScan-wait
    parameters:
      maxDuration: 10
  - type: export
    parameters:
      context: juice-shop
      type: url
      source: all
      fileName: /zap/wrk/zap-endpoints.txt
    alwaysRun: true
  - type: export
    parameters:
      context: juice-shop
      type: yaml
      source: sitestree
      fileName: /zap/wrk/zap-site-tree.yaml
    alwaysRun: true
  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/wrk
      reportFile: zap.json
      displayReport: false
    alwaysRun: true
