---
env:
  contexts:
    - name: juice-shop
      urls:
        - http://juice-shop:3000
      includePaths:
        - '^http://juice-shop:3000(?:$|[/?#].*)$'
  configs:
    view.mode: protect
    scanner.maxScanDurationInMins: 30
  parameters:
    failOnError: true
    failOnWarning: false
    continueOnFailure: false
    progressToStdout: true

jobs:
  - type: passiveScan-config
    parameters:
      scanOnlyInScope: true
  - type: spider
    parameters:
      context: juice-shop
      url: http://juice-shop:3000
      maxDuration: 10
  - type: spiderClient
    parameters:
      context: juice-shop
      url: http://juice-shop:3000
      maxDuration: 10
      scopeCheck: Strict
  - type: passiveScan-wait
    parameters:
      maxDuration: 10
  - type: activeScan
    parameters:
      context: juice-shop
      url: http://juice-shop:3000
  - type: passiveScan-wait
    parameters:
      maxDuration: 10
  - type: export
    parameters:
      context: juice-shop
      type: url
      source: all
      fileName: /zap/wrk/zap-endpoints.txt
    alwaysRun: true
  - type: export
    parameters:
      context: juice-shop
      type: yaml
      source: sitestree
      fileName: /zap/wrk/zap-site-tree.yaml
    alwaysRun: true
  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/wrk
      reportFile: zap.json
      displayReport: false
    alwaysRun: true
